- name: Add Credential on the Wallet
  ansible.builtin.shell:
    chdir: "{{ wallet_base }}"
    #cmd: echo "{{ wallet_loop.username}} {{wallet_loop.tnsnames}}  {{wallet_loop.password}}" >> out2.txt
    cmd: echo {{ wallet_password }} | {{ mkstore_path }}/mkstore -wrl {{ wallet_base }}/{{ wallet_name }} -createCredential {{ wallet_loop.tnsnames}} {{wallet_loop.username}}  {{wallet_loop.password}}
  with_items: "{{ wallet }}"
  loop_control:
    loop_var: wallet_loop
  become: true
  become_user: oracle
  tags:
  - create-wallet
  - add_credintial_wallet